version: '2.4'

networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24

volumes:
  zookeeper-data:
  kafka-data:
  postgres-data:

services:
  postgres:
    image: postgres:13.1-alpine
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 11001:5432
    networks:
      - main
  kafka:
    image: bitnami/kafka:2.6.0-debian-10-r91
    restart: on-failure
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CLIENT_USER=local
      - KAFKA_CLIENT_PASSWORD=local
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:11002
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - kafka-data:/bitnami
    ports:
      - 11002:9093
    networks:
      - main

  zookeeper:
    image: bitnami/zookeeper:3.6.1-debian-10-r60
    restart: on-failure
    environment:
      - ALLOW_ANONYMOUS_LOGIN=true
    volumes:
      - zookeeper-data:/bitnami
    networks:
      - main

  zk-web:
    image: tobilg/zookeeper-webui
    restart: on-failure
    environment:
      - ZK_DEFAULT_NODE=zookeeper:2181
    ports:
      - 12001:8080
    networks:
      - main

  kafdrop:
    image: obsidiandynamics/kafdrop:3.27.0
    restart: on-failure
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
    ports:
      - 12002:9000
    networks:
      - main
