#!/usr/bin/env sh

get_kafdrop_status() {
  curl -s -o /dev/null -I -H "Accept: text/xml" -w "%{http_code}" http://localhost:12002
}

echo "starting core services..."
docker-compose -f docker-compose.yaml up -d postgres kafka zookeeper zk-web kafdrop

while [ "$(get_kafdrop_status)" -ne "200" ]; do
  echo "waiting for kafka..."
  sleep 5
done
